https://www.youtube.com/watch?v=GB9ByFAIAH4&t=5s (37:23)

In [1]:
import numpy as np
import sys

## The Basics

In [5]:
a = np.array([[1,2,3],[4,5,3]], dtype='int8')
print(a)

[[1 2 3]
 [4 5 3]]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
print(b.ndim)
# Get Shape
print(a.shape)

2
(3,)


In [25]:
# Get type
a.dtype

dtype('int8')

In [21]:
# Get size
print(a.itemsize)

# Get total size
print(a.size * a.itemsize)

print(a.nbytes)

4
12
12


## Accessing/Changing specific elements, rows, columns...

In [2]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
# Get a specific element [r,c]
a[1,5]

13

In [28]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [30]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [33]:
a[1,5] = 20
print(a)

a[:,2] = [5,6]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  6 11 12 20 14]]


## 3D example

In [3]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [13]:
# Get specific element
b[0,3,1]

8

## Initializing Different Types of Arrays

In [24]:
# All 0s matrix
np.zeros(((2,3,2)))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [30]:
# All 1s matrix
np.ones((4,2,2), dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [32]:
# Any other number
np.full((2,2), 8, dtype='float32')

array([[8., 8.],
       [8., 8.]], dtype=float32)

In [7]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [2]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.79495012, 0.00451502],
       [0.41519721, 0.6821929 ],
       [0.84351638, 0.44194916],
       [0.74799302, 0.43872645]])

In [3]:
# Random integer values
np.random.randint(-4,8, size=(2,2))

array([[ 2,  3],
       [ 4, -4]])

In [4]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Mathematics

In [8]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a+2

array([3, 4, 5, 6])

In [10]:
a*2

array([2, 4, 6, 8])

In [11]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [3]:
a**2

array([[  1,   4,   9,  16,  25,  36,  49],
       [ 64,  81, 100, 121, 144, 169, 196]], dtype=int32)

In [4]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021, -0.53657292,
         0.42016704,  0.99060736]])

## Linear Algebra

In [8]:
a = np.ones((2,3))

b = np.full((3,2),2)

In [11]:
# Multiplication
a @ b
# Same thing but other way
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [12]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statitstics

In [13]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.min(stats, axis=1)

array([1, 4])

In [18]:
np.max(stats,axis=1)

array([3, 6])

In [19]:
np.sum(stats)

21

## Reorganizing Arrays

In [27]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Vertically stacking vector

In [29]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

## Horizontal stack

In [30]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

In [35]:
# Load Data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## Boolean Masking and Advanced Indexing

In [38]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [41]:
# You can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [43]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [45]:
((filedata < 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])